services:
  - type: web
    name: calendar-oauth-api
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./app.db

